version: "2"
services:
  avatars_micrservs:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - ROOT_PATH=/
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - TOKEN_CHECK=2e3852bfdd5ac217592feb198051f8a8
  db:
    image: postgres:13
    volumes:
      - "./db:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=postgres"
      - "POSTGRES_PORT=5432"